CBMC proofs for aws_cryptosdk_session_set_commitment_policy, aws_cryptosdk_priv_algorithm_allowed_for_{encrypt,decrypt}
aws/aws-encryption-sdk-c pull request #633
Opened 2020-11-19 06:02 UTC by tegansb

*Description of changes:*
CBMC harnesses and Makefiles for aws_cryptosdk_session_set_commitment_policy, aws_cryptosdk_priv_algorithm_allowed_for_encrypt, aws_cryptosdk_priv_algorithm_allowed_for_decrypt. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2020-11-21 20:01 UTC, feliperodri requested changes

2020-11-21 20:01 UTC, feliperodri commented on verification/cbmc/proofs/aws_cryptosdk_session_set_commitment_policy/README.md
> +    * abort is called from unexplored cases of aws_cryptosdk_priv_session_change_state.
```Markdown
# Memory safety proof for `aws_cryptosdk_session_set_commitment_policy`

This proof harness attains 40% code coverage.  The following comments explain
why the uncovered lines of code are unreachable code.

Some functions contain unreachable blocks of code:

* `aws_cryptosdk_priv_session_change_state`

    * Called from `aws_cryptosdk_priv_fail_session` with the argument `new_state` hard-coded to `ST_ERROR`. 
    * Only one case of the switch statement on `new_state` is therefore covered. 
    * Additionally, the current state is not `ST_CONFIG` from a conditional check in `aws_cryptosdk_session_set_commitment_policy`. 

Some functions are never reached:

* `abort()`

    * `abort()` is called from unexplored cases of `aws_cryptosdk_priv_session_change_state`.
```

2020-11-22 19:50 UTC, tegansb commented on verification/cbmc/proofs/aws_cryptosdk_priv_algorithm_allowed_for_decrypt/cbmc-batch.yaml
> +report_memory: 32000
I see, I have replaced all yamls with the standard file!

2020-11-22 19:51 UTC, tegansb commented on verification/cbmc/proofs/aws_cryptosdk_priv_algorithm_allowed_for_encrypt/cbmc-batch.yaml
> +report_memory: 32000
Updated!

2020-11-22 19:51 UTC, tegansb commented on verification/cbmc/proofs/aws_cryptosdk_session_set_commitment_policy/cbmc-batch.yaml
> +report_memory: 32000
Updated!

2020-11-22 20:45 UTC, tegansb commented on verification/cbmc/proofs/aws_cryptosdk_session_set_commitment_policy/aws_cryptosdk_session_set_commitment_policy_harness.c
> +    __CPROVER_assume(session != NULL);
We do now :) I forgot to push the commit adding session.c

2020-11-22 20:47 UTC, tegansb commented on verification/cbmc/proofs/aws_cryptosdk_session_set_commitment_policy/aws_cryptosdk_session_set_commitment_policy_harness.c
> +    if (ret == AWS_OP_SUCCESS) {
Updated!

2020-11-22 20:51 UTC, tegansb commented on verification/cbmc/proofs/aws_cryptosdk_session_set_commitment_policy/README.md
> +    * abort is called from unexplored cases of aws_cryptosdk_priv_session_change_state.
Updated!

2020-11-24 19:19 UTC, alex-chew approved these changes
LGTM

2020-11-25 19:39 UTC, feliperodri approved these changes

2020-11-25 23:06 UTC, merged